name: Publish Snapshot
on: [push]

jobs:
  build:
    strategy:
      matrix:
        # Keep the matrix for when jdk 17 rc come out
        java: [17]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
      - name: Generate build number for branch
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.github_token }}
          prefix: ${{ github.ref }}
      - run: ./gradlew checkLicenses generateQmj --parallel --stacktrace
      - run: ./gradlew build --stacktrace --parallel
      - run: ./gradlew publish --stacktrace --parrallel
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: ./*/build/libs/
