name: Test
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        # Keep the matrix for when jdk 17 rc come out
        java: [17, 18]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
      - name: Generate build number for branch
        if: ${{ github.event.organization == "QuiltMC" }}
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.github_token }}
          prefix: ${{ github.ref }}
      - name: Check
        run: ./gradlew checkLicenses generateQmj check --parallel --stacktrace
      - name: Build
        run: ./gradlew build publishToMavenLocal --parallel --stacktrace
      - run: mkdir run && echo "eula=true" >> run/eula.txt
      - name: Test
        run: ./gradlew :runAutoTestServer --stacktrace
      - name: Publish
        if: ${{ github.event.organization == "QuiltMC" }}
        run: ./gradlew publish --parallel --stacktrace
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      - uses: actions/upload-artifact@v3
        with:
          name: Production Mods
          path: |
            ./**/build/libs/
            !./build-logic/**
            !./**/build/libs/*-javadoc.jar
            !./**/build/libs/*-sources.jar
            !./**/build/libs/*-testmod.jar
      - uses: actions/upload-artifact@v3
        with:
          name: Test Mods
          path: ./**/build/libs/*-testmod.jar
